# Invite: https://discord.com/oauth2/authorize?client_id=<id>&permissions=8&scope=bot%20applications.commands

token: TOKEN # Bot token

inviteFormat: https://discord.com/oauth2/authorize?client_id=%id%&permissions=8&scope=bot%20applications.commands # Invite format (%id% will be replaced with bot id)
language: 'config/language.yml' # Langage file

version: 1.0.0 # Version (don't modify this value)