token: TOKEN # Bot token

embedColor: '#19AFFF'   # Colors for embed messages
commandPrefix: '!'      # Prefix for commands
owner: 'Ghexter'        # Who owns this bot

adminOnlyCommands:    # Restrict commands for admin only
  - 'stop'
  - 'reload'

moderatorOnlyCommands: # Command for moderator with kick and ban perms
  - 'version'
  - 'ban'
  - 'kick'

blacklistChannels:            # Ignored channels based on IDs
  enabled: false               # Enable blacklisted channels
  channels: []                # List of blacklisted channels
  convertToWhitelist: false   # Convert channels to whitelisted channels

inviteFormat: https://discord.com/oauth2/authorize?client_id=%id%&permissions=8&scope=bot   # Invite format for bot
language: 'config/language.yml'                                                              # Langage file 

version: 1.0.0    # Version (don't modify this value)