token: TOKEN # Bot token

embedColor: '#19AFFF'  # Colors for embed messages
commandPrefix: '!'  # Prefix for commands
owner: 'Ghexter'  # Who owns this bot

guildId: # Only register slash commands for the given guild.

# Command permissions
permissions:
  # Message commands permissions
  messageCommands:
    # Enable message command permissions
    enable: true

    # Restrict commands for admin only (This is the command name)
    adminOnlyCommands: ['stop']

    # Command for moderator with kick and ban perms (This is the command name)
    moderatorOnlyCommands: []
  
  # Slash commands permissions
  interactionCommands:
    # Enable slash commands permissions
    enable: true

    # Register slash commands
    registerSlashCommands: true

    # Restrict commands for admin only (This is the command name)
    adminOnlyCommands: ['stop']

    # Command for moderator with kick and ban perms (This is the command name)
    moderatorOnlyCommands: []

# Ignored channels based on IDs
blacklistChannels:            
  enabled: false  # Enable blacklisted channels

  # List of blacklisted channels
  channels: []
  convertToWhitelist: false  # Convert channels to whitelisted channels

# Custom bot presence
presence:
  enabled: true  # Enable presence
  status: ['online']  # Status of bot (online, idle, dnd, offline)  [this can be a string or an object for random value]
  type: ['playing']  # Type of status (playing, listening, watching, streaming) or enter a custom status  [this can be a string or an object for random value]
  activityName: ['Minecraft']  # Name your activity [this can be a string or an object for random value]


# Danger Zone!
# Edit this values below if you know what you're doing

# process errors logging. (Few options can stop some crashes)
processErrors:
  clientShardError: true
  processWarning: true
  processUnhandledRejection: false
  processUncaughtException: false

inviteFormat: https://discord.com/oauth2/authorize?client_id=%id%&permissions=8&scope=bot%20applications.commands   # Invite format for bot
language: 'config/language.yml'   # Langage file 
modulesFolder: 'modules'  # Define where's your modules

version: 1.4.2    # Version (don't modify this value)