token: TOKEN # Bot token

embedColor: '#19AFFF'   # Colors for embed messages
commandPrefix: '>'      # Prefix for commands

blacklistChannels:            # Ignored channels
  enabled: true               # Enable blacklisted channels
  channels: []                # List of blacklisted channels
  convertToWhitelist: false   # Convert channels to whitelisted channels

inviteFormat: https://discord.com/oauth2/authorize?client_id=%id%&permissions=8&scope=bot   # Invite format for bot
language: 'config/language.yml'                                                              # Langage file 

version: 1.0.0    # Version (don't modify this value)