stop: 
  - 'Stopping <:oke:888823666228486195>'
  - 'Shutting down <:wehdikashore:900367488636813343>'
  - 'Signing out as a bot <:tologobooo:881023181354319893>'
error:
  - 'An error occurred <a:thicc_sugoma:857953871384018964>'
  - 'Error occurred <:omegalol:886695211747672095>'
  - 'Oppss an error occurred <:tologobooo:881023181354319893>'
  - 'Error! <:e:888823666400452619>'
thinking: 
  - 'I''m thonking wait... <:tologobooo:881023181354319893>'
  - 'wait breh <a:loading:870586127973756949>'
  - ':brain: <a:loading:870586127973756949>'
noPerms:
  - 'No permissions <:e:888823666400452619>'
  - 'lul no permissions'
  - 'NO PERMMSSS! <:omegalol:886695211747672095>'
  - 'Error: **NO PERMS!** <:omegalol:886695211747672095>'
reload: 
  requested: 
    - 'ok <a:boi_scrollright:898522330786070568>'
    - 'bruh oki :point_right: :point_left:'
    - 'FINEE! <:boi:891291989335748650>'
  success: 
    - 'bot has been destroyed and recreated <a:thicc_sugoma:857953871384018964>'
    - 'reloaded you poor bitch <:boi:891291989335748650>'
    - 'Bot was reloaded <:gihun:899026746693787648>'
help:
  title: 'Command Help'
  description: 'Here''s a list of the current commands:'
langs:
  title: 'Language codes list'
  description: 'Here''s a list of language codes `Add an argument to filter list`:'


version: 1.0.0 # Version (don't modify this value)