reload: 
  requested: 
    - ok <a:boi_scrollright:898522330786070568>
    - breuh you bitch
    - ok <:boi:891291989335748650>
  success: 
    - Your bitch bot has been destroyed and recreated <a:thicc_sugoma:857953871384018964>
    - reloaded poor bitch <:boi:891291989335748650>
    - 'lul :middle_finger:'

version: 1.0.0 # Version (don't modify this value)